Force decrypt_kernel to use python2
malus-security/iExtractor pull request #13
Opened 2020-07-18 12:24 UTC by andreicalin-georgescu

Proposes a change to line 34 in bin/decrypt_kernel to explicitly use python2 when running get_lzss_section_offset.py script

2020-07-18 14:10 UTC, razvand commented
@andreicalin-georgescu , it would be best if we used Python3 throughout the scripts. Could you please update the `get_lszz_section_offset.py` script to use Python3? And then call it using `python3` from `bin/decrypt_kernel`.

2020-07-18 15:25 UTC, andreicalin-georgescu commented
@razvand I made the changes to the scripts. Everything seems to be working on my end.

2020-08-09 16:42 UTC, razvand requested changes
Add minor feedback on presentation and formatting.

2020-08-09 16:42 UTC, razvand commented on bin/decrypt_kernel
> +lzss_offset=$(python3 ./get_lzss_section_offset.py "$kernelcache_decrypted")
Please also update the shebang line in `bin/get_lzss_section_offset.py` to `#!/usr/bin/env python3`.

2020-08-09 16:42 UTC, razvand commented on bin/get_lzss_section_offset.py
> +                        print (offset+i)
Use `print(offeset+i)`, remove blank before paranthesis.

2020-08-09 16:43 UTC, razvand commented
@andreicalin-georgescu , please squash your commits into a single commit for this pull request.

2020-08-10 08:46 UTC, andreicalin-georgescu commented
Presentation and formatting changed according to feedback. Hope everything's all right now. Sorry for the oversight on my part.

2020-08-10 10:16 UTC, razvand approved these changes
All good

2020-08-10 10:16 UTC, merged