Fix realpath and tac missing on OSX
malus-security/iExtractor pull request #17
Opened 2021-11-18 20:58 UTC by davidxbors

2022-03-23 07:14 UTC, razvand requested changes
Please update the commit message. The commit line looks good. But you need a more detailed description about what the commit does. Mention the requirement for the `coreutils` package to include the `realpath` and the `tac` executable files.

2022-03-23 07:14 UTC, razvand commented on README.md
> +or the following commands on macOS using [MacPorts](https://www.macports.org/) and [Homebrew](https://brew.sh/):
Isn't there a `coreutils` package as part of MacPorts?

2022-03-23 14:42 UTC, davidxbors commented on README.md
> +or the following commands on macOS using [MacPorts](https://www.macports.org/) and [Homebrew](https://brew.sh/):
I provided a description to the commit that answers your question.

2022-04-13 12:33 UTC, razvand approved these changes
All good. Thanks, @davidxbors

2022-04-13 12:33 UTC, merged